import { Database, RefreshCcw, Shield } from 'lucide-react';

export default function Settings() {
    return (
        <div className="flex w-full flex-col gap-6 pb-28">
            <section className="hero-panel p-6 sm:p-8">
                <div className="section-kicker">Settings</div>
                <h1 className="mt-3 font-display text-4xl font-bold tracking-tight text-white">Operational controls</h1>
                <p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">
                    Keep the app lightweight: the dashboard reads from the imported dataset and refresh controls help you pull the latest standings.
                </p>
            </section>

            <section className="grid gap-4 lg:grid-cols-3">
                <Panel icon={<Database className="h-5 w-5 text-cyan-300" aria-hidden="true" />} title="Data Source" description="Session data is loaded from public/data.json, which is generated by the WhatsApp import bot." />
                <Panel icon={<Shield className="h-5 w-5 text-emerald-300" aria-hidden="true" />} title="Consistency" description="Standings, history, and player profiles all derive from the same imported session dataset." />
                <Panel icon={<RefreshCcw className="h-5 w-5 text-amber-200" aria-hidden="true" />} title="Refresh" description="Use pull-to-refresh in the main views whenever you want to re-fetch the latest published data." />
            </section>
        </div>
    );
}

function Panel({ icon, title, description, children }) {
    return (
        <article className="glass-panel p-6">
            <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-950/60">{icon}</div>
            <h2 className="mt-5 font-display text-2xl font-bold text-white">{title}</h2>
            <p className="mt-3 text-sm leading-7 text-slate-300">{description}</p>
            {children}
        </article>
    );
}